### ISSUE TITLE
docker pull 找不到

### ISSUE THREAD

**Issue by qqhexuan** [ZHENFENG13/My-Blog#80]
在docker hub 里没有找到 blog/my-blog 这个image,请问是不是有变化?

**Comment by ZHENFENG13** [comment]
我用的是阿里云的私有仓库，没有传到dockerhub：
```
mysql:
  image: registry.cn-hangzhou.aliyuncs.com/13/myblog:mysql

 #测试时使用
  ports:
   - 13306:3306

my-blog:
  image: registry.cn-hangzhou.aliyuncs.com/13/myblog:blog
  ports:
   - 28080:8080
  links:
   - mysql

```
